import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import {
  regions,
  venues,
  events,
  itineraries,
  olympicsUpdates,
  systemConfig,
} from "./schema";

async function seed() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error("DATABASE_URL is not set");
  }

  const client = postgres(connectionString, { max: 1 });
  const db = drizzle(client);

  console.log("Seeding database...");

  // ── REGIONS (7) ──────────────────────────────────────────────────
  await db.insert(regions).values([
    {
      id: "brisbane",
      name: "Brisbane",
      description: "Brisbane's food scene has quietly become one of Australia's best. The craft beer situation at Felons is world-class and the riverfront precincts are unmissable.",
      latitude: "-27.4705",
      longitude: "153.0260",
      zoomLevel: 11,
      bomStationId: "IDQ65388",
      bestTimeToVisit: "September-November",
      insiderSummary: "Brisbane's food scene has quietly become one of Australia's best. Skip the tourist traps in South Bank and head to James Street or Howard Smith Wharves. The craft beer situation at Felons is world-class.",
      displayOrder: 1,
    },
    {
      id: "gold-coast",
      name: "Gold Coast",
      description: "Everyone thinks Gold Coast is just theme parks — wrong. Burleigh Heads is the real heart with incredible food, the best headland walk in QLD, and Tallebudgera Creek is paradise.",
      latitude: "-28.0167",
      longitude: "153.4000",
      zoomLevel: 11,
      bomStationId: "IDQ65395",
      bestTimeToVisit: "September-November",
      insiderSummary: "Everyone thinks Gold Coast is just theme parks. Wrong. Burleigh Heads is the real heart — incredible food, the best headland walk in QLD, and Tallebudgera Creek is paradise. The hinterland is underrated.",
      displayOrder: 2,
    },
    {
      id: "sunshine-coast",
      name: "Sunshine Coast",
      description: "Noosa gets the headlines but the real Sunshine Coast is the hinterland — Maleny, Montville, Eumundi. Spirit House in Yandina is one of the best dining experiences in Queensland.",
      latitude: "-26.6500",
      longitude: "153.0667",
      zoomLevel: 11,
      bomStationId: "IDQ65362",
      bestTimeToVisit: "September-November",
      insiderSummary: "Noosa gets the headlines but the real Sunshine Coast is the hinterland — Maleny, Montville, Eumundi. Spirit House in Yandina is one of the best dining experiences in Queensland, full stop.",
      displayOrder: 3,
    },
    {
      id: "tropical-north-qld",
      name: "Tropical North Queensland",
      description: "Cairns is the gateway but Port Douglas is where you want to stay. The Daintree is genuinely like nowhere else on Earth.",
      latitude: "-16.9186",
      longitude: "145.7781",
      zoomLevel: 11,
      bomStationId: "IDQ65268",
      bestTimeToVisit: "March-November",
      insiderSummary: "Cairns is the gateway but Port Douglas is where you want to stay. The Daintree is genuinely like nowhere else on Earth. Rusty's Markets on a Saturday morning is pure tropical magic.",
      displayOrder: 4,
    },
    {
      id: "whitsundays",
      name: "Whitsundays",
      description: "Whitehaven Beach is not overhyped — it really is that good. Hill Inlet at high tide is the shot. Fish D'vine and the Sailing Club are gems.",
      latitude: "-20.2800",
      longitude: "148.9500",
      zoomLevel: 11,
      bomStationId: "IDQ65316",
      bestTimeToVisit: "September-November",
      insiderSummary: "Whitehaven Beach is not overhyped — it really is that good. Hill Inlet at high tide is the shot. Airlie Beach itself is backpacker-heavy but Fish D'vine and the Sailing Club are gems.",
      displayOrder: 5,
    },
    {
      id: "fraser-coast",
      name: "Fraser Coast",
      description: "Hervey Bay is the whale watching capital of Australia, July to November. K'gari is a UNESCO World Heritage island you can actually drive on.",
      latitude: "-25.2900",
      longitude: "152.8500",
      zoomLevel: 11,
      bomStationId: "IDQ65354",
      bestTimeToVisit: "September-November",
      insiderSummary: "Hervey Bay is the whale watching capital of Australia, July to November. K'gari is a UNESCO World Heritage island you can actually drive on. This whole region is massively underrated.",
      displayOrder: 6,
    },
    {
      id: "outback-qld",
      name: "Outback Queensland",
      description: "Longreach and Winton are bucket-list Australia. The Australian Age of Dinosaurs museum in Winton is world-class.",
      latitude: "-23.4400",
      longitude: "144.2500",
      zoomLevel: 11,
      bomStationId: "IDQ65404",
      bestTimeToVisit: "May-September",
      insiderSummary: "Longreach and Winton are bucket-list Australia. The Australian Age of Dinosaurs museum in Winton is world-class. The Stockman's Hall of Fame will change how you see this country.",
      displayOrder: 7,
    },
  ]).onConflictDoNothing();

  console.log("✓ 7 regions seeded");

  // ── VENUES (50) ──────────────────────────────────────────────────
  // BRISBANE (10)
  const brisbaneVenues = [
    {
      name: "Howard Smith Wharves",
      slug: "howard-smith-wharves",
      regionId: "brisbane",
      suburb: "New Farm",
      type: "restaurant",
      cuisine: "modern-australian",
      priceLevel: "moderate",
      suntimesRating: "8.5",
      insiderTip: "Skip the main restaurants — the craft beer garden at Felons is the real move. Sunset views are unbeatable.",
      description: "Heritage-listed riverside precinct under the Story Bridge with multiple restaurants, bars, and a craft brewery.",
      tags: ["waterfront", "date-night", "drinks"],
    },
    {
      name: "Gauge",
      slug: "gauge",
      regionId: "brisbane",
      suburb: "South Brisbane",
      type: "restaurant",
      cuisine: "modern-australian",
      priceLevel: "upscale",
      suntimesRating: "9.0",
      insiderTip: "The tasting menu changes weekly and never disappoints. Book the counter seats to watch the kitchen.",
      description: "Contemporary Australian fine dining in Fish Lane. Seasonal tasting menus with exceptional wine pairing.",
      tags: ["fine-dining", "date-night", "foodie"],
    },
    {
      name: "Happy Boy",
      slug: "happy-boy",
      regionId: "brisbane",
      suburb: "Fortitude Valley",
      type: "restaurant",
      cuisine: "chinese",
      priceLevel: "moderate",
      suntimesRating: "8.5",
      insiderTip: "Best Chinese in Brisbane and it's not close. The dan dan noodles are mandatory. Cash only on weekends.",
      description: "Modern Chinese restaurant in the Valley. No-frills interior, exceptional food. Where chefs eat on nights off.",
      tags: ["asian", "budget-eats", "local-favourite"],
    },
    {
      name: "New Farm Deli",
      slug: "new-farm-deli",
      regionId: "brisbane",
      suburb: "New Farm",
      type: "cafe",
      cuisine: "cafe-brunch",
      priceLevel: "moderate",
      suntimesRating: "8.0",
      insiderTip: "Been here since 1975. The cannoli alone is worth the trip. Grab a table outside on a weekday morning.",
      description: "Brisbane institution since 1975. Italian deli, cafe, and grocer. The cannoli is famous for a reason.",
      tags: ["brunch", "heritage", "family-friendly"],
    },
    {
      name: "GOMA",
      slug: "goma",
      regionId: "brisbane",
      suburb: "South Brisbane",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "9.0",
      insiderTip: "Free entry and world-class exhibitions. The kids' gallery on Level 1 is genuinely brilliant — not an afterthought.",
      description: "Gallery of Modern Art — Queensland's flagship contemporary art gallery. Free permanent collection plus touring exhibitions.",
      tags: ["free", "family-friendly", "rainy-day", "culture"],
    },
    {
      name: "Eat Street Northshore",
      slug: "eat-street-northshore",
      regionId: "brisbane",
      suburb: "Hamilton",
      type: "market",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "8.0",
      insiderTip: "Friday and Saturday nights. Get the dumplings from the stall near the entrance, then work your way through. Allow 2 hours.",
      description: "Hawker-style dining market in repurposed shipping containers on the waterfront. 50+ food stalls, live music.",
      tags: ["markets", "street-food", "date-night", "family-friendly"],
    },
    {
      name: "Kangaroo Point Cliffs",
      slug: "kangaroo-point-cliffs",
      regionId: "brisbane",
      suburb: "Kangaroo Point",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "8.5",
      insiderTip: "The walk from the cliffs to South Bank at sunset is our favourite free activity in Brisbane. Period.",
      description: "Dramatic cliff face on the Brisbane River with walking paths, picnic areas, and the best city panorama.",
      tags: ["free", "outdoors", "sunset", "photography"],
    },
    {
      name: "James Street Precinct",
      slug: "james-street-precinct",
      regionId: "brisbane",
      suburb: "Fortitude Valley",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "7.5",
      insiderTip: "Brisbane's best dining strip. Start at Biàng for noodles, end at Gerard's Bar for wine. Don't rush it.",
      description: "Fortitude Valley's premier dining, shopping, and lifestyle precinct. A walkable strip of Brisbane's best.",
      tags: ["dining", "shopping", "nightlife"],
    },
    {
      name: "Jan Powers Farmers Markets",
      slug: "jan-powers-farmers-markets",
      regionId: "brisbane",
      suburb: "CBD",
      type: "market",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "8.0",
      insiderTip: "Every Saturday at the Powerhouse. The sourdough from Flour & Chocolate sells out by 9am. Get there early.",
      description: "Brisbane's premier farmers market at the Brisbane Powerhouse in New Farm. Local produce and artisan foods.",
      tags: ["markets", "brunch", "family-friendly", "local-produce"],
    },
    {
      name: "Montrachet",
      slug: "montrachet",
      regionId: "brisbane",
      suburb: "Bowen Hills",
      type: "restaurant",
      cuisine: "french",
      priceLevel: "upscale",
      suntimesRating: "9.0",
      insiderTip: "Brisbane's best French restaurant. The wine list alone is worth the visit. Thursday evenings are magic.",
      description: "Classic French bistro with an extraordinary wine cellar. Consistently one of Brisbane's top restaurants for a decade.",
      tags: ["fine-dining", "date-night", "wine"],
    },
  ];

  // GOLD COAST (10)
  const goldCoastVenues = [
    {
      name: "Rick Shores",
      slug: "rick-shores",
      regionId: "gold-coast",
      suburb: "Burleigh Heads",
      type: "restaurant",
      cuisine: "asian",
      priceLevel: "upscale",
      suntimesRating: "9.5",
      insiderTip: "Modern Asian with ocean views. The bug roll is iconic. Book 3 weeks ahead for dinner — or walk in at lunch.",
      description: "Beachfront modern Asian restaurant. One of the best restaurants in Queensland. The Moreton Bay bug roll is legendary.",
      tags: ["fine-dining", "waterfront", "date-night"],
    },
    {
      name: "Fishmongers Wife",
      slug: "fishmongers-wife",
      regionId: "gold-coast",
      suburb: "Burleigh Heads",
      type: "restaurant",
      cuisine: "seafood",
      priceLevel: "budget",
      suntimesRating: "8.5",
      insiderTip: "Best fish and chips on the coast. Grab them, walk to the headland, find a rock. That's your evening sorted.",
      description: "No-fuss takeaway fish and chips at the base of Burleigh Headland. The freshest catch cooked simply and perfectly.",
      tags: ["budget-eats", "takeaway", "family-friendly"],
    },
    {
      name: "The Tropic",
      slug: "the-tropic",
      regionId: "gold-coast",
      suburb: "Burleigh Heads",
      type: "bar",
      cuisine: null,
      priceLevel: "moderate",
      suntimesRating: "8.0",
      insiderTip: "Saturday night live music is the move. Great cocktails, no pretension. The Gold Coast as it should be.",
      description: "Relaxed tropical bar in the heart of Burleigh. Live music on weekends, craft cocktails, and genuine vibes.",
      tags: ["drinks", "nightlife", "live-music"],
    },
    {
      name: "Paddock Bakery",
      slug: "paddock-bakery",
      regionId: "gold-coast",
      suburb: "Miami",
      type: "cafe",
      cuisine: "cafe-brunch",
      priceLevel: "budget",
      suntimesRating: "9.0",
      insiderTip: "This bakery turned into a destination. The cruffin is famous for a reason. Go weekday morning to avoid the queue.",
      description: "Destination bakery-cafe in Miami. The cruffins and pastries are extraordinary. Weekend queues are long but worth it.",
      tags: ["brunch", "bakery", "instagram"],
    },
    {
      name: "Burleigh Headland National Park",
      slug: "burleigh-headland",
      regionId: "gold-coast",
      suburb: "Burleigh Heads",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "9.5",
      insiderTip: "Walk the full loop track (30 min). Tuesday arvo for the best sunset with the fewest people. We'll die on this hill.",
      description: "Coastal national park with a loop walking track, ocean views, and one of the best sunsets in Queensland.",
      tags: ["free", "outdoors", "sunset", "photography", "walking"],
    },
    {
      name: "Tallebudgera Creek",
      slug: "tallebudgera-creek",
      regionId: "gold-coast",
      suburb: "Burleigh Heads",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "9.0",
      insiderTip: "The best swimming spot on the Gold Coast and most visitors miss it entirely. Flat water, shaded banks, paradise.",
      description: "Crystal-clear tidal creek with calm swimming, shaded picnic areas, and no crowds. The Gold Coast's best secret.",
      tags: ["free", "swimming", "family-friendly", "hidden-gem"],
    },
    {
      name: "Tamborine Mountain Distillery",
      slug: "tamborine-mountain-distillery",
      regionId: "gold-coast",
      suburb: "Tamborine Mountain",
      type: "attraction",
      cuisine: null,
      priceLevel: "moderate",
      suntimesRating: "7.5",
      insiderTip: "Combine with the Gallery Walk for a full hinterland day. The liqueur tasting flight is surprisingly good.",
      description: "Small-batch distillery on Tamborine Mountain. Tasting flights, hinterland views, and a great day trip.",
      tags: ["drinks", "hinterland", "day-trip"],
    },
    {
      name: "Village Markets",
      slug: "village-markets",
      regionId: "gold-coast",
      suburb: "Burleigh Heads",
      type: "market",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "8.0",
      insiderTip: "First and third Saturday of each month at Burleigh Heads State School. Local designers, food trucks, live music.",
      description: "Curated artisan market with local designers, vintage finds, food trucks, and live music.",
      tags: ["markets", "shopping", "family-friendly"],
    },
    {
      name: "Social Eating House + Bar",
      slug: "social-eating-house",
      regionId: "gold-coast",
      suburb: "Gold Coast",
      type: "restaurant",
      cuisine: "modern-australian",
      priceLevel: "upscale",
      suntimesRating: "8.5",
      insiderTip: "Fine dining without the stuffiness. The tasting menu with wine pairing is genuinely world-class.",
      description: "Award-winning fine dining. Seasonal tasting menus that rival anything in Sydney or Melbourne.",
      tags: ["fine-dining", "date-night", "foodie"],
    },
    {
      name: "Nobby Beach Social",
      slug: "nobby-beach-social",
      regionId: "gold-coast",
      suburb: "Nobby Beach",
      type: "restaurant",
      cuisine: "modern-australian",
      priceLevel: "moderate",
      suntimesRating: "8.0",
      insiderTip: "Locals' favourite. Less Instagram, more substance. The breakfast menu is strong and never crowded before 9.",
      description: "Neighbourhood restaurant with strong breakfast and dinner menus. Where locals actually eat.",
      tags: ["brunch", "local-favourite", "family-friendly"],
    },
  ];

  // SUNSHINE COAST (10)
  const sunshineCoastVenues = [
    {
      name: "Noosa Farmers Market",
      slug: "noosa-farmers-market",
      regionId: "sunshine-coast",
      suburb: "Noosa",
      type: "market",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "9.0",
      insiderTip: "Every Sunday morning. Come hungry. The mushroom toastie from the stall near the back is our annual highlight.",
      description: "Premier Sunshine Coast farmers market at Noosa Lions Park with local produce, artisan food, and excellent coffee.",
      tags: ["markets", "brunch", "family-friendly", "local-produce"],
    },
    {
      name: "Eumundi Markets",
      slug: "eumundi-markets",
      regionId: "sunshine-coast",
      suburb: "Eumundi",
      type: "market",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "9.0",
      insiderTip: "Wednesday and Saturday. 600+ stalls. Been running for 50 years. Organic coffee near the entrance, then wander.",
      description: "Iconic Sunshine Coast market since the 1970s. Over 600 stalls of art, craft, food, and music.",
      tags: ["markets", "shopping", "culture", "must-visit"],
    },
    {
      name: "Spirit House",
      slug: "spirit-house",
      regionId: "sunshine-coast",
      suburb: "Yandina",
      type: "restaurant",
      cuisine: "thai",
      priceLevel: "upscale",
      suntimesRating: "9.0",
      insiderTip: "Thai food in a rainforest setting with koi ponds. It shouldn't work but it absolutely does. Book well ahead.",
      description: "Thai restaurant in a tropical garden with koi ponds. One of Queensland's most unique dining experiences.",
      tags: ["fine-dining", "unique-experience", "date-night"],
    },
    {
      name: "Sails Restaurant",
      slug: "sails-restaurant",
      regionId: "sunshine-coast",
      suburb: "Noosa",
      type: "restaurant",
      cuisine: "seafood",
      priceLevel: "luxury",
      suntimesRating: "8.5",
      insiderTip: "Fine dining right on Noosa Main Beach. The seafood is flawless. Lunch is better value than dinner.",
      description: "Iconic beachfront fine dining on Hastings Street. Exceptional seafood with direct beach views.",
      tags: ["fine-dining", "waterfront", "special-occasion"],
    },
    {
      name: "Hastings Street",
      slug: "hastings-street",
      regionId: "sunshine-coast",
      suburb: "Noosa",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "7.5",
      insiderTip: "The main strip. Good for a browse but the real Noosa is off the beaten track — ask us for the local spots.",
      description: "Noosa's main dining and shopping strip. Boutiques, restaurants, and beach access.",
      tags: ["shopping", "dining", "tourist"],
    },
    {
      name: "Noosa National Park",
      slug: "noosa-national-park",
      regionId: "sunshine-coast",
      suburb: "Noosa",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "9.5",
      insiderTip: "The coastal walk is Queensland's best short hike. Dolphins from the headland, koalas in the trees. Allow 2 hours.",
      description: "Stunning coastal national park. The Coastal Walk to Hell's Gates is unmissable.",
      tags: ["free", "outdoors", "walking", "wildlife", "must-visit"],
    },
    {
      name: "Glass House Mountains",
      slug: "glass-house-mountains",
      regionId: "sunshine-coast",
      suburb: "Glass House Mountains",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "8.5",
      insiderTip: "Drive through and stop at Mary Cairncross Reserve for the panorama. Mt Ngungun is the best walk (1.5 hrs return).",
      description: "Dramatic volcanic peaks. Sacred to the Jinibara and Kabi Kabi peoples. Stunning walking and photography.",
      tags: ["free", "outdoors", "walking", "photography"],
    },
    {
      name: "Mooloolaba Beach",
      slug: "mooloolaba-beach",
      regionId: "sunshine-coast",
      suburb: "Mooloolaba",
      type: "beach",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "8.5",
      insiderTip: "The most swimmable beach on the Sunshine Coast. Protected waters, great for families. Fish and chips on the esplanade after.",
      description: "Protected north-facing beach with calm swimming, lifeguard patrols, and a lively esplanade.",
      tags: ["free", "beach", "family-friendly", "swimming"],
    },
    {
      name: "Maleny Dairies",
      slug: "maleny-dairies",
      regionId: "sunshine-coast",
      suburb: "Maleny",
      type: "attraction",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "8.0",
      insiderTip: "Working dairy farm you can visit. The chocolate milk is legendary. Kids love it. Combine with a Maleny wander.",
      description: "Working dairy farm in the hinterland offering tours and tastings. Their chocolate milk is a regional icon.",
      tags: ["family-friendly", "hinterland", "local-produce"],
    },
    {
      name: "The Canteen",
      slug: "the-canteen",
      regionId: "sunshine-coast",
      suburb: "Noosa",
      type: "cafe",
      cuisine: "cafe-brunch",
      priceLevel: "moderate",
      suntimesRating: "8.0",
      insiderTip: "Hidden behind Hastings Street. Better coffee than the main strip and half the price. Locals only vibe.",
      description: "Tucked-away cafe behind Noosa's main street. Excellent coffee and food without the premium.",
      tags: ["brunch", "hidden-gem", "local-favourite"],
    },
  ];

  // TROPICAL NORTH QLD (10)
  const tnqVenues = [
    {
      name: "Rusty's Markets",
      slug: "rustys-markets",
      regionId: "tropical-north-qld",
      suburb: "Cairns",
      type: "market",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "9.0",
      insiderTip: "Friday, Saturday, Sunday. The tropical fruit here is unreal — try the black sapote (chocolate pudding fruit). Get there early.",
      description: "Cairns' iconic tropical produce market. Exotic fruit, local produce, and multicultural food stalls.",
      tags: ["markets", "local-produce", "must-visit"],
    },
    {
      name: "Cairns Esplanade Lagoon",
      slug: "cairns-esplanade-lagoon",
      regionId: "tropical-north-qld",
      suburb: "Cairns",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "8.5",
      insiderTip: "Free saltwater pool right on the waterfront. The best free attraction in Cairns. Pack a picnic.",
      description: "Free public swimming lagoon on the Cairns waterfront. Saltwater pool with ocean views and playgrounds.",
      tags: ["free", "swimming", "family-friendly"],
    },
    {
      name: "Ochre Restaurant",
      slug: "ochre-restaurant",
      regionId: "tropical-north-qld",
      suburb: "Cairns",
      type: "restaurant",
      cuisine: "modern-australian",
      priceLevel: "upscale",
      suntimesRating: "8.5",
      insiderTip: "Modern Australian using native ingredients. Crocodile, kangaroo, wattleseed — done properly. Not gimmicky.",
      description: "Pioneer of native Australian cuisine. Bush tucker ingredients in sophisticated modern dishes for over 25 years.",
      tags: ["fine-dining", "unique-experience", "native-food"],
    },
    {
      name: "Daintree Ice Cream Company",
      slug: "daintree-ice-cream-co",
      regionId: "tropical-north-qld",
      suburb: "Daintree",
      type: "cafe",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "8.0",
      insiderTip: "They grow the fruit on site. The black sapote and wattleseed flavours are incredible. Mandatory Daintree stop.",
      description: "Family-run ice cream shop growing their own tropical fruit. Unique flavours you won't find anywhere else.",
      tags: ["family-friendly", "local-produce", "unique-experience"],
    },
    {
      name: "Port Douglas Sunday Markets",
      slug: "port-douglas-markets",
      regionId: "tropical-north-qld",
      suburb: "Port Douglas",
      type: "market",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "8.5",
      insiderTip: "Every Sunday under the trees. Great local art, tropical fruit, and baked goods. Relaxed Port Douglas vibes.",
      description: "Weekly market under the mango trees. Local art, tropical produce, handmade goods, and live music.",
      tags: ["markets", "local-produce", "arts"],
    },
    {
      name: "Green Island",
      slug: "green-island",
      regionId: "tropical-north-qld",
      suburb: "Great Barrier Reef",
      type: "attraction",
      cuisine: null,
      priceLevel: "moderate",
      suntimesRating: "8.0",
      insiderTip: "45 min ferry from Cairns. Snorkelling right off the beach — no boat needed. Go morning for clearest water.",
      description: "Coral cay on the Great Barrier Reef, 45 minutes from Cairns. Walk-in snorkelling and rainforest walks.",
      tags: ["reef", "snorkelling", "day-trip", "nature"],
    },
    {
      name: "Kuranda Scenic Railway",
      slug: "kuranda-scenic-railway",
      regionId: "tropical-north-qld",
      suburb: "Kuranda",
      type: "attraction",
      cuisine: null,
      priceLevel: "moderate",
      suntimesRating: "8.5",
      insiderTip: "One of Australia's great train rides. Through rainforest and past waterfalls. Take train up, Skyrail back.",
      description: "Heritage railway through World Heritage rainforest from Cairns to Kuranda. Spectacular views.",
      tags: ["scenic", "heritage", "day-trip", "family-friendly"],
    },
    {
      name: "Flames of the Forest",
      slug: "flames-of-the-forest",
      regionId: "tropical-north-qld",
      suburb: "Port Douglas",
      type: "experience",
      cuisine: null,
      priceLevel: "luxury",
      suntimesRating: "9.0",
      insiderTip: "Outdoor dining literally in the rainforest. Aboriginal cultural experience included. Book weeks ahead — worth every dollar.",
      description: "Unique dining experience in the Daintree with Indigenous cultural performances and fire-cooked food.",
      tags: ["unique-experience", "fine-dining", "culture", "special-occasion"],
    },
    {
      name: "Prawn Star",
      slug: "prawn-star",
      regionId: "tropical-north-qld",
      suburb: "Cairns",
      type: "restaurant",
      cuisine: "seafood",
      priceLevel: "budget",
      suntimesRating: "8.0",
      insiderTip: "A prawn trawler converted into a restaurant. Sit on the boat, eat prawns straight off the catch. BYO. Classic Cairns.",
      description: "Converted fishing trawler at Cairns Marina serving fresh prawns and seafood. BYO, no bookings.",
      tags: ["budget-eats", "unique-experience", "seafood", "waterfront"],
    },
    {
      name: "Crystal Cascades",
      slug: "crystal-cascades",
      regionId: "tropical-north-qld",
      suburb: "Cairns",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "8.5",
      insiderTip: "A series of swimming holes 20 min from Cairns CBD. Locals' secret — barely any tourists. Best on a weekday morning.",
      description: "Freshwater swimming holes and waterfalls surrounded by rainforest, 20 minutes from Cairns.",
      tags: ["free", "swimming", "hidden-gem", "nature"],
    },
  ];

  // WHITSUNDAYS (10)
  const whitsundaysVenues = [
    {
      name: "Whitehaven Beach",
      slug: "whitehaven-beach",
      regionId: "whitsundays",
      suburb: "Whitsunday Island",
      type: "beach",
      cuisine: null,
      priceLevel: "moderate",
      suntimesRating: "10.0",
      insiderTip: "The whitest sand in the world. Hill Inlet lookout at high tide is the money shot. Full-day boat trip is the way.",
      description: "Seven kilometres of pure white silica sand. Consistently rated one of the world's best beaches.",
      tags: ["beach", "must-visit", "photography", "bucket-list"],
    },
    {
      name: "Airlie Beach Lagoon",
      slug: "airlie-beach-lagoon",
      regionId: "whitsundays",
      suburb: "Airlie Beach",
      type: "attraction",
      cuisine: null,
      priceLevel: "free",
      suntimesRating: "8.0",
      insiderTip: "Free infinity pool overlooking the ocean. The heart of Airlie Beach. Sunset sessions are a local tradition.",
      description: "Free public lagoon pool on the foreshore with ocean views, BBQs, and tropical gardens.",
      tags: ["free", "swimming", "family-friendly"],
    },
    {
      name: "Fish D'vine",
      slug: "fish-dvine",
      regionId: "whitsundays",
      suburb: "Airlie Beach",
      type: "restaurant",
      cuisine: "seafood",
      priceLevel: "moderate",
      suntimesRating: "8.5",
      insiderTip: "Best seafood in Airlie. The rum bar upstairs is an unexpected gem. Try the Coral Trout if it's on the menu.",
      description: "Airlie Beach's best seafood restaurant with an incredible rum bar upstairs.",
      tags: ["seafood", "date-night", "drinks"],
    },
    {
      name: "Fat Frog Beach Cafe",
      slug: "fat-frog-beach-cafe",
      regionId: "whitsundays",
      suburb: "Airlie Beach",
      type: "cafe",
      cuisine: "cafe-brunch",
      priceLevel: "budget",
      suntimesRating: "7.5",
      insiderTip: "Solid brekkie with ocean views. Not fancy, just good. The big breakfast fuels a full day of island hopping.",
      description: "Casual beachside cafe. Reliable breakfast and coffee with water views.",
      tags: ["brunch", "budget-eats", "waterfront"],
    },
    {
      name: "Whitsunday Sailing Club",
      slug: "whitsunday-sailing-club",
      regionId: "whitsundays",
      suburb: "Airlie Beach",
      type: "bar",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "7.5",
      insiderTip: "Cheapest beers in Airlie with the best sunset views. Where the locals actually drink. Wednesday night trivia.",
      description: "Members and visitors welcome. Cheapest drinks in town with unbeatable sunset views over the marina.",
      tags: ["drinks", "budget-eats", "sunset", "local-favourite"],
    },
    {
      name: "Daydream Island Resort",
      slug: "daydream-island-resort",
      regionId: "whitsundays",
      suburb: "Daydream Island",
      type: "accommodation",
      cuisine: null,
      priceLevel: "luxury",
      suntimesRating: "8.0",
      insiderTip: "Recently renovated. The living reef is amazing for families. Close enough for a day trip but better overnight.",
      description: "Renovated island resort with a living coral reef lagoon, restaurants, and water sports.",
      tags: ["accommodation", "family-friendly", "resort"],
    },
    {
      name: "Heart Reef",
      slug: "heart-reef",
      regionId: "whitsundays",
      suburb: "Great Barrier Reef",
      type: "attraction",
      cuisine: null,
      priceLevel: "luxury",
      suntimesRating: "9.0",
      insiderTip: "Natural heart-shaped coral formation. Scenic helicopter flight is the only way to see it properly. Bucket list.",
      description: "Naturally formed heart-shaped coral reef. Iconic aerial view via helicopter or seaplane.",
      tags: ["bucket-list", "photography", "scenic", "unique-experience"],
    },
    {
      name: "Mr Bones",
      slug: "mr-bones",
      regionId: "whitsundays",
      suburb: "Airlie Beach",
      type: "restaurant",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "8.0",
      insiderTip: "Best pizza in the Whitsundays. The outdoor seating on the main strip is great for people-watching.",
      description: "Wood-fired pizza on Airlie Beach's main street. Great pizza, cold beers, lively atmosphere.",
      tags: ["budget-eats", "family-friendly", "casual"],
    },
    {
      name: "Airlie Beach Markets",
      slug: "airlie-beach-markets",
      regionId: "whitsundays",
      suburb: "Airlie Beach",
      type: "market",
      cuisine: null,
      priceLevel: "budget",
      suntimesRating: "7.0",
      insiderTip: "Saturday mornings. Small but good. Local art, tropical produce, handmade jewellery.",
      description: "Weekly Saturday morning market on the foreshore. Local art, tropical fruit, handmade goods.",
      tags: ["markets", "shopping"],
    },
    {
      name: "Ocean Rafting",
      slug: "ocean-rafting",
      regionId: "whitsundays",
      suburb: "Airlie Beach",
      type: "experience",
      cuisine: null,
      priceLevel: "moderate",
      suntimesRating: "9.0",
      insiderTip: "The best day trip operator in the Whitsundays. Northern or Southern exposure tour — both hit Whitehaven Beach.",
      description: "Adventure day trips to Whitehaven Beach and the outer reef. Fast boats, snorkelling, beach time.",
      tags: ["adventure", "day-trip", "reef", "snorkelling", "must-visit"],
    },
  ];

  const allVenues = [
    ...brisbaneVenues,
    ...goldCoastVenues,
    ...sunshineCoastVenues,
    ...tnqVenues,
    ...whitsundaysVenues,
  ];

  await db.insert(venues).values(allVenues).onConflictDoNothing();
  console.log(`✓ ${allVenues.length} venues seeded`);

  // ── ITINERARIES (5) ──────────────────────────────────────────────
  await db.insert(itineraries).values([
    {
      title: "Brisbane Weekend Foodie Escape",
      slug: "brisbane-weekend-foodie",
      regionId: "brisbane",
      durationDays: 2,
      description: "A two-day deep dive into Brisbane's booming food scene — from farmers markets to fine dining.",
      targetAudience: "foodies",
      budgetLevel: "moderate",
      bestSeason: "September-November",
      totalEstimatedCost: "$300-500pp",
      isFeatured: true,
      days: JSON.stringify([
        {
          day: 1,
          title: "Markets & Culture",
          stops: [
            { time: "8:00am", venueSlug: "jan-powers-farmers-markets", activity: "Saturday farmers market", tip: "The sourdough from Flour & Chocolate sells out by 9am", cost: "$20-30" },
            { time: "10:00am", venueSlug: "james-street-precinct", activity: "James Street brunch", tip: "Try Biàng for noodles", cost: "$25-40" },
            { time: "2:00pm", venueSlug: "goma", activity: "Gallery of Modern Art", tip: "Free entry — check what's on", cost: "Free" },
            { time: "5:00pm", venueSlug: "howard-smith-wharves", activity: "Sunset drinks at Felons", tip: "The craft beer garden, not the restaurants", cost: "$30-50" },
          ],
        },
        {
          day: 2,
          title: "Neighbourhood Gems",
          stops: [
            { time: "8:30am", venueSlug: "new-farm-deli", activity: "Brekkie at an institution", tip: "The cannoli is mandatory", cost: "$15-25" },
            { time: "10:00am", venueSlug: "kangaroo-point-cliffs", activity: "Cliffs walk to South Bank", tip: "Our favourite free activity in Brisbane", cost: "Free" },
            { time: "7:00pm", venueSlug: "gauge", activity: "Fine dining at Gauge", tip: "Book counter seats to watch the kitchen", cost: "$120-180" },
          ],
        },
      ]),
    },
    {
      title: "Gold Coast 3-Day Family Adventure",
      slug: "gold-coast-family-3day",
      regionId: "gold-coast",
      durationDays: 3,
      description: "Three days exploring the Gold Coast beyond the theme parks — headlands, hinterland, and hidden swimming spots.",
      targetAudience: "families",
      budgetLevel: "moderate",
      bestSeason: "September-November",
      totalEstimatedCost: "$400-700pp",
      isFeatured: true,
      days: JSON.stringify([
        {
          day: 1,
          title: "Headland Day",
          stops: [
            { time: "8:00am", venueSlug: "burleigh-headland", activity: "Burleigh Headland walk", tip: "Full loop track, 30 minutes", cost: "Free" },
            { time: "12:00pm", venueSlug: "fishmongers-wife", activity: "Fish and chips lunch", tip: "Best on the coast. Eat on the headland.", cost: "$15-25" },
            { time: "2:00pm", venueSlug: "tallebudgera-creek", activity: "Swimming at Tallebudgera Creek", tip: "Flat water, shaded banks — paradise", cost: "Free" },
          ],
        },
        {
          day: 2,
          title: "Hinterland Escape",
          stops: [
            { time: "9:00am", venueSlug: "tamborine-mountain-distillery", activity: "Tamborine Mountain full day", tip: "Combine Gallery Walk with distillery tasting", cost: "$30-50" },
          ],
        },
        {
          day: 3,
          title: "Coast & Markets",
          stops: [
            { time: "8:00am", venueSlug: "paddock-bakery", activity: "Brekkie at Paddock Bakery", tip: "Go weekday morning to avoid the queue. The cruffin is famous.", cost: "$15-25" },
            { time: "11:00am", venueSlug: "mooloolaba-beach", activity: "Beach time at Mooloolaba", tip: "Most swimmable beach on the coast", cost: "Free" },
            { time: "2:00pm", venueSlug: "village-markets", activity: "Village Markets if Saturday", tip: "1st and 3rd Saturday each month", cost: "Free entry" },
          ],
        },
      ]),
    },
    {
      title: "Sunshine Coast Hidden Gems",
      slug: "sunshine-coast-hidden-gems",
      regionId: "sunshine-coast",
      durationDays: 2,
      description: "Two days uncovering the real Sunshine Coast — beyond Hastings Street to the hinterland and hidden cafes.",
      targetAudience: "couples",
      budgetLevel: "moderate",
      bestSeason: "September-November",
      totalEstimatedCost: "$250-450pp",
      isFeatured: true,
      days: JSON.stringify([
        {
          day: 1,
          title: "Markets & Mountains",
          stops: [
            { time: "8:00am", venueSlug: "eumundi-markets", activity: "Eumundi Markets", tip: "600+ stalls. Organic coffee near the entrance.", cost: "Free entry" },
            { time: "12:00pm", venueSlug: "spirit-house", activity: "Lunch at Spirit House", tip: "Thai food in a rainforest with koi ponds. Book ahead.", cost: "$60-90" },
            { time: "5:00pm", venueSlug: "glass-house-mountains", activity: "Glass House Mountains sunset", tip: "Mary Cairncross Reserve for the panorama", cost: "Free" },
          ],
        },
        {
          day: 2,
          title: "Noosa Trails",
          stops: [
            { time: "7:00am", venueSlug: "noosa-national-park", activity: "Noosa National Park coastal walk", tip: "Dolphins from the headland, koalas in the trees", cost: "Free" },
            { time: "10:00am", venueSlug: "the-canteen", activity: "Brunch at The Canteen", tip: "Hidden behind Hastings Street. Locals only.", cost: "$20-35" },
            { time: "12:00pm", venueSlug: "noosa-farmers-market", activity: "Noosa Farmers Market if Sunday", tip: "The mushroom toastie stall", cost: "Free entry" },
          ],
        },
      ]),
    },
    {
      title: "Cairns to Cape Tribulation",
      slug: "cairns-to-cape-trib",
      regionId: "tropical-north-qld",
      durationDays: 3,
      description: "Three days from Cairns to the Daintree — reef, rainforest, and the best of Tropical North Queensland.",
      targetAudience: "families",
      budgetLevel: "moderate",
      bestSeason: "March-November",
      totalEstimatedCost: "$500-900pp",
      isFeatured: true,
      days: JSON.stringify([
        {
          day: 1,
          title: "Cairns Essentials",
          stops: [
            { time: "9:00am", venueSlug: "cairns-esplanade-lagoon", activity: "Cairns Esplanade swim", tip: "Free saltwater pool right on the waterfront", cost: "Free" },
            { time: "11:00am", venueSlug: "rustys-markets", activity: "Rusty's Markets", tip: "Try the black sapote — chocolate pudding fruit", cost: "$10-20" },
            { time: "7:00pm", venueSlug: "ochre-restaurant", activity: "Dinner at Ochre", tip: "Native ingredients done properly", cost: "$60-100" },
          ],
        },
        {
          day: 2,
          title: "Reef Day",
          stops: [
            { time: "8:00am", venueSlug: "green-island", activity: "Green Island snorkelling full day", tip: "45 min ferry. Snorkelling right off the beach.", cost: "$90-120" },
            { time: "7:00pm", venueSlug: "prawn-star", activity: "Dinner at Prawn Star", tip: "Prawns on a trawler. BYO. Classic Cairns.", cost: "$25-40" },
          ],
        },
        {
          day: 3,
          title: "Rainforest Drive",
          stops: [
            { time: "8:00am", venueSlug: null, activity: "Daintree drive north", tip: "Stop at the Daintree River ferry crossing", cost: "$30 ferry" },
            { time: "11:00am", venueSlug: "daintree-ice-cream-co", activity: "Daintree Ice Cream Company", tip: "They grow the fruit on site", cost: "$10-15" },
            { time: "1:00pm", venueSlug: null, activity: "Cape Tribulation beach", tip: "Where the rainforest meets the reef", cost: "Free" },
            { time: "4:00pm", venueSlug: "crystal-cascades", activity: "Crystal Cascades swim", tip: "20 min from Cairns. Locals' secret.", cost: "Free" },
          ],
        },
      ]),
    },
    {
      title: "Whitsundays Sailing Trip",
      slug: "whitsundays-sailing",
      regionId: "whitsundays",
      durationDays: 3,
      description: "Three days in the Whitsundays — Whitehaven Beach, the Great Barrier Reef, and Airlie Beach at sunset.",
      targetAudience: "couples",
      budgetLevel: "moderate",
      bestSeason: "September-November",
      totalEstimatedCost: "$600-1500pp",
      isFeatured: true,
      days: JSON.stringify([
        {
          day: 1,
          title: "Arrive & Settle",
          stops: [
            { time: "2:00pm", venueSlug: "airlie-beach-lagoon", activity: "Airlie Beach Lagoon swim", tip: "Free infinity pool overlooking the ocean", cost: "Free" },
            { time: "7:00pm", venueSlug: "fish-dvine", activity: "Dinner at Fish D'vine", tip: "Best seafood in Airlie. Rum bar upstairs.", cost: "$50-80" },
          ],
        },
        {
          day: 2,
          title: "Island Day",
          stops: [
            { time: "8:00am", venueSlug: "ocean-rafting", activity: "Ocean Rafting day trip", tip: "Northern or Southern exposure — both hit Whitehaven", cost: "$180-250" },
            { time: "11:00am", venueSlug: "whitehaven-beach", activity: "Whitehaven Beach & Hill Inlet", tip: "Hill Inlet at high tide is the money shot", cost: "Included" },
          ],
        },
        {
          day: 3,
          title: "Sky & Sea",
          stops: [
            { time: "8:00am", venueSlug: "heart-reef", activity: "Heart Reef scenic flight (optional)", tip: "Bucket list. Helicopter is the only way.", cost: "$250-400" },
            { time: "4:00pm", venueSlug: "whitsunday-sailing-club", activity: "Sunset beers at the Sailing Club", tip: "Cheapest beers in Airlie. Best sunset views.", cost: "$15-25" },
          ],
        },
      ]),
    },
  ]).onConflictDoNothing();

  console.log("✓ 5 itineraries seeded");

  // ── EVENTS (8 recurring) ────────────────────────────────────────
  await db.insert(events).values([
    {
      name: "Eumundi Markets",
      slug: "eumundi-markets-event",
      regionId: "sunshine-coast",
      suburb: "Eumundi",
      category: "markets",
      description: "Iconic Sunshine Coast market since the 1970s. Over 600 stalls of art, craft, food, and music.",
      venueName: "Eumundi Markets",
      address: "80 Memorial Drive, Eumundi QLD 4562",
      isRecurring: true,
      recurrencePattern: "Every Wednesday & Saturday",
      price: "Free",
      isSuntimesPick: true,
      insiderTip: "Saturday is bigger but Wednesday is less crowded.",
      startDate: new Date("2025-01-01"),
    },
    {
      name: "Eat Street Northshore",
      slug: "eat-street-northshore-event",
      regionId: "brisbane",
      suburb: "Hamilton",
      category: "food",
      description: "Hawker-style dining market in repurposed shipping containers on the waterfront. 50+ food stalls, live music.",
      venueName: "Eat Street Northshore",
      address: "221D MacArthur Ave, Hamilton QLD 4007",
      isRecurring: true,
      recurrencePattern: "Every Friday & Saturday",
      price: "$5 entry",
      isSuntimesPick: true,
      insiderTip: "Get the dumplings near the entrance.",
      startDate: new Date("2025-01-03"),
    },
    {
      name: "Jan Powers Farmers Markets",
      slug: "jan-powers-farmers-markets-event",
      regionId: "brisbane",
      suburb: "New Farm",
      category: "markets",
      description: "Brisbane's premier farmers market at the Brisbane Powerhouse. Local produce and artisan foods.",
      venueName: "Brisbane Powerhouse",
      address: "119 Lamington Street, New Farm QLD 4005",
      isRecurring: true,
      recurrencePattern: "Every Saturday",
      price: "Free",
      isSuntimesPick: true,
      insiderTip: "Sourdough sells out by 9am.",
      startDate: new Date("2025-01-04"),
    },
    {
      name: "Noosa Farmers Market",
      slug: "noosa-farmers-market-event",
      regionId: "sunshine-coast",
      suburb: "Noosa",
      category: "markets",
      description: "Premier Sunshine Coast farmers market with local produce, artisan food, and excellent coffee.",
      venueName: "Noosa Lions Park",
      address: "Noosa Lions Park, Noosaville QLD 4566",
      isRecurring: true,
      recurrencePattern: "Every Sunday",
      price: "Free",
      isSuntimesPick: true,
      insiderTip: "Come hungry. Mushroom toastie stall is the highlight.",
      startDate: new Date("2025-01-05"),
    },
    {
      name: "Rusty's Markets",
      slug: "rustys-markets-event",
      regionId: "tropical-north-qld",
      suburb: "Cairns",
      category: "markets",
      description: "Cairns' iconic tropical produce market. Exotic fruit, local produce, and multicultural food stalls.",
      venueName: "Rusty's Markets",
      address: "57-89 Grafton Street, Cairns QLD 4870",
      isRecurring: true,
      recurrencePattern: "Every Fri, Sat, Sun",
      price: "Free",
      isSuntimesPick: true,
      insiderTip: "Saturday morning is peak. Try the black sapote.",
      startDate: new Date("2025-01-03"),
    },
    {
      name: "Village Markets Burleigh",
      slug: "village-markets-burleigh-event",
      regionId: "gold-coast",
      suburb: "Burleigh Heads",
      category: "markets",
      description: "Curated artisan market with local designers, vintage finds, food trucks, and live music.",
      venueName: "Burleigh Heads State School",
      address: "1750 Gold Coast Highway, Burleigh Heads QLD 4220",
      isRecurring: true,
      recurrencePattern: "1st & 3rd Saturday",
      price: "Free",
      isSuntimesPick: false,
      insiderTip: "Local designers and food trucks.",
      startDate: new Date("2025-01-04"),
    },
    {
      name: "Cairns Night Markets",
      slug: "cairns-night-markets-event",
      regionId: "tropical-north-qld",
      suburb: "Cairns",
      category: "markets",
      description: "Nightly markets in the heart of Cairns with food, souvenirs, and massage.",
      venueName: "Cairns Night Markets",
      address: "71-75 The Esplanade, Cairns QLD 4870",
      isRecurring: true,
      recurrencePattern: "Every evening",
      price: "Free",
      isSuntimesPick: false,
      insiderTip: "Tourist-heavy but worth a wander.",
      startDate: new Date("2025-01-01"),
    },
    {
      name: "Airlie Beach Markets",
      slug: "airlie-beach-markets-event",
      regionId: "whitsundays",
      suburb: "Airlie Beach",
      category: "markets",
      description: "Weekly Saturday morning market on the foreshore with local art and tropical produce.",
      venueName: "Airlie Beach Foreshore",
      address: "The Esplanade, Airlie Beach QLD 4802",
      isRecurring: true,
      recurrencePattern: "Every Saturday",
      price: "Free",
      isSuntimesPick: false,
      insiderTip: "Small but good local art.",
      startDate: new Date("2025-01-04"),
    },
  ]).onConflictDoNothing();

  console.log("✓ 8 events seeded");

  // ── OLYMPICS UPDATES (5) ─────────────────────────────────────────
  await db.insert(olympicsUpdates).values([
    {
      title: "Brisbane Arena — Victoria Park",
      category: "venue",
      regionId: "brisbane",
      content: "New 17,000-seat arena under construction. Will host swimming, gymnastics, basketball finals. Completion 2031.",
      publishedDate: new Date("2025-01-15"),
      isFeatured: true,
    },
    {
      title: "Cross River Rail",
      category: "infrastructure",
      regionId: "brisbane",
      content: "6 new stations, 10km of rail connecting Olympic venues. The Gabba 2 minutes from CBD by train. On track for 2032.",
      publishedDate: new Date("2025-02-01"),
      isFeatured: true,
    },
    {
      title: "The Gabba Redevelopment",
      category: "venue",
      regionId: "brisbane",
      content: "Main athletics stadium for 2032. Design phase underway. Focus on legacy use for sports and entertainment.",
      publishedDate: new Date("2025-03-01"),
      isFeatured: true,
    },
    {
      title: "Cairns Basketball Preliminaries",
      category: "venue",
      regionId: "tropical-north-qld",
      content: "Cairns Convention Centre confirmed for basketball preliminary rounds. Thousands of international visitors to TNQ.",
      publishedDate: new Date("2025-04-01"),
      isFeatured: false,
    },
    {
      title: "Gold Coast Venue Upgrades",
      category: "venue",
      regionId: "gold-coast",
      content: "2018 Commonwealth Games venues being upgraded. Coomera Indoor Sports Centre and Robina Stadium confirmed.",
      publishedDate: new Date("2025-05-01"),
      isFeatured: false,
    },
  ]).onConflictDoNothing();

  console.log("✓ 5 olympics updates seeded");

  // ── SYSTEM CONFIG ────────────────────────────────────────────────
  await db.insert(systemConfig).values([
    { key: "emergency_mode", value: "false" },
    { key: "max_replies_per_day", value: "50" },
    { key: "min_priority_score", value: "25" },
  ]).onConflictDoNothing();

  console.log("✓ System config seeded");
  console.log("Seed complete!");

  await client.end();
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
